const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'')}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const slotNames=['早餐','上午','午餐','下午','晚餐','晚上'],slotIcons=['🍳','🌅','🍜','☀️','🍽️','🌙'];
const defaultSlots=()=>slotNames.map((n,i)=>({name:n,icon:slotIcons[i],value:i===0?'飯店早餐':'待安排',meta:'點擊可修改',done:false}));
const curated=[
['churaumi','景點','美麗海水族館','本部','🐋','親子熱門 · 北部核心','Okinawa Churaumi Aquarium',['親子','雨天']],['kouri','景點','古宇利島','今歸仁','🌊','海景 · 自駕推薦','Kouri Island',['海景']],['manza','景點','萬座毛','恩納','🌅','海岸景觀 · 短程停留','Cape Manzamo',['海景','長輩']],['ryukyu','景點','琉球村','恩納','🏮','文化體驗 · 親子','Ryukyu Mura',['親子']],['bios','景點','Bios之丘','石川','🌿','自然 · 小孩放電','Bios no Oka',['親子']],['american','購物','美國村','北谷','🎡','購物 · 餐廳 · 夜景','American Village Okinawa',['夜景','購物']],['kokusai','購物','國際通','那霸','🛍️','伴手禮 · 晚餐方便','Kokusai-dori Okinawa',['購物','雨天']],['parco','購物','PARCO CITY','浦添','🏬','大型商場 · 雨天首選','San-A Urasoe West Coast PARCO CITY',['雨天','親子']],['gyokusendo','景點','沖繩世界・玉泉洞','南城','🪨','洞穴室內 · 南部路線','Okinawa World',['雨天','親子']],['senaga','景點','瀨長島 Umikaji Terrace','豐見城','✈️','近機場 · 夕陽','Umikaji Terrace',['海景','機場']],['shuri','景點','首里城公園','那霸','🏯','歷史文化 · 步行較多','Shurijo Castle Park',['文化']],['dmm','景點','DMM Kariyushi 水族館','豐見城','🐠','室內 · 近機場 · 雨天','DMM Kariyushi Aquarium',['親子','雨天']],['pineapple','景點','名護鳳梨園','名護','🍍','親子熱門 · 北部順遊','Nago Pineapple Park',['親子']],['neo','景點','Neo Park Okinawa','名護','🦩','動物互動 · 親子','Neo Park Okinawa',['親子']],['zoo','景點','沖繩兒童王國','沖繩市','🦁','動物園＋兒童設施','Okinawa Zoo Museum',['親子']],['botanical','景點','東南植物樂園','沖繩市','🌴','植物園 · 夜間點燈季','Southeast Botanical Gardens Okinawa',['親子','夜景']],['zanpa','景點','殘波岬','讀谷','🌊','海岸景觀 · 自駕','Cape Zanpa',['海景']],['sefa','景點','齋場御嶽','南城','⛩️','世界遺產 · 南部文化','Sefa Utaki',['文化']],['gangala','景點','Gangala之谷','南城','🌳','森林洞穴導覽 · 建議預約','Valley of Gangala',['自然']],['makishi','景點','第一牧志公設市場','那霸','🐟','市場美食 · 國際通順遊','Makishi Public Market',['美食','雨天']],['teamlab','景點','teamLab Future Park Okinawa','那霸','✨','室內互動 · 親子雨天','teamLab Future Park Okinawa',['親子','雨天']],['soba','美食','沖繩そば','全島','🍜','家庭餐 · 午餐首選','Okinawa soba',['親子']],['steak','美食','沖繩牛排','那霸','🥩','晚餐熱門','Okinawa steak',['晚餐']],['taco','美食','塔可飯','中部','🌮','快速 · 小孩好分食','Taco rice Okinawa',['親子']]
].map(x=>({id:x[0],type:x[1],title:x[2],area:x[3],emoji:x[4],meta:x[5],query:x[6],tags:x[7]}));
const expenseNames=['機票','住宿','租車','飲食','門票','購物','其他'];
const state={tab:'today',day:1,days:read('okinawa-days',5),plans:read('okinawa-plans',{}),flights:read('okinawa-flights',{outbound:{},return:{}}),stays:read('okinawa-stays',[]),meta:read('okinawa-meta',{startDate:'',endDate:'',transport:'自駕',rentalCompany:'',pickup:'',dropoff:'',budgetTarget:120000}),party:read('okinawa-party',[{name:'旅伴 1',type:'成人',age:'',notes:''},{name:'旅伴 2',type:'成人',age:'',notes:''},{name:'小朋友',type:'兒童',age:'3',notes:''}]),family:read('okinawa-family',{toddler:true,elderly:false,stroller:true,nap:true,relaxed:true}),expenses:read('okinawa-expenses',Object.fromEntries(expenseNames.map(x=>[x,0]))),weather:{temp:'--',text:'更新中'},explore:{q:'',filter:'全部',online:null,loading:false,error:'',selected:null,adding:false},custom:read('okinawa-custom-places',[]),hidden:read('okinawa-hidden-places',[]),modal:null,ai:null};
const trip=()=>state.plans[state.day]||defaultSlots();
function persist(){write('okinawa-days',state.days);write('okinawa-plans',state.plans);write('okinawa-flights',state.flights);write('okinawa-stays',state.stays);write('okinawa-meta',state.meta);write('okinawa-party',state.party);write('okinawa-family',state.family);write('okinawa-expenses',state.expenses);write('okinawa-custom-places',state.custom);write('okinawa-hidden-places',state.hidden)}
function updateTrip(list){state.plans={...state.plans,[state.day]:list};write('okinawa-plans',state.plans);render()}
function dayTabs(){return `<div class="dayTabs">${Array.from({length:state.days},(_,i)=>i+1).map(d=>`<button class="dayBtn ${d===state.day?'selected':''}" onclick="app.setDay(${d})">DAY ${d}</button>`).join('')}</div>`}
function header(){let title=state.tab==='today'?'今日行程':state.tab==='trip'?'旅行設定':state.tab==='map'?'今日路線':state.tab==='explore'?'探索沖繩':'緊急協助';return `<header class="header"><div><span class="kicker">OKINAWA · INDEPENDENT · V3.0</span><h1>${title}</h1></div><button class="avatar" onclick="app.tab('trip')">👨‍👩‍👦</button></header>`}
function nav(){return `<nav class="nav">${[['today','☀️','TODAY'],['trip','📅','TRIP'],['map','🗺️','MAP'],['explore','✨','EXPLORE'],['sos','🆘','SOS']].map(([id,ic,l])=>`<button class="${state.tab===id?'active':''}" onclick="app.tab('${id}')"><span style="font-size:20px">${ic}</span><span>${l}</span></button>`).join('')}</nav>`}
function today(){const t=trip(),done=t.filter(x=>x.done).length;return `${dayTabs()}<div class="hero"><div><b>DAY ${state.day}</b><span>沖繩 · Family Trip</span></div><div class="weather"><span>☀️</span><b>${state.weather.temp}</b><span>${state.weather.text}</span></div></div><div class="quick"><span>🚗 六段式自由行</span><span class="ok">✓ ${done}/${t.length} 完成</span></div><div class="progress"><i style="width:${done/t.length*100}%"></i></div><div>${t.map((s,i)=>`<div class="slot ${s.done?'done':''}"><button class="check ${s.done?'checked':''}" onclick="app.toggle(${i})">${s.done?'✓':''}</button><div class="slotIcon" onclick="app.editSlot(${i})">${s.icon}</div><div class="slotBody" onclick="app.editSlot(${i})"><small>${esc(s.name)}</small><b>${esc(s.value)}</b><span>${esc(s.done?'已完成':s.meta)}</span></div><span>›</span></div>`).join('')}</div>${state.ai?.applied?`<div class="notice">✨ 已套用 AI 完整行程，可逐天微調。</div>`:''}`}
function card(icon,title,main,sub,id){return `<button class="card" onclick="app.open('${id}')"><span class="lead">${icon}</span><div><small>${title}</small><b>${esc(main)}</b><span>${esc(sub)}</span></div><span>›</span></button>`}
function tripView(){const total=Object.values(state.expenses).reduce((a,b)=>a+Number(b||0),0),staySub=state.stays.length?state.stays.map(s=>`D${s.fromDay}–${s.toDay} ${s.hotel||'未命名'}`).join(' · '):'可設定不同 Day 住不同飯店';return `<button class="aiLaunch" onclick="app.openAI()"><span class="lead">✨</span><div><small>AI PLAN</small><b>AI 自動規劃整趟行程</b><span>讀取航班、住宿、同行者與 Family Mode</span></div><span>›</span></button>${card('✈️','FLIGHTS',state.flights.outbound?.flight||state.flights.return?.flight?'航班已設定':'設定去程 / 回程航班',state.flights.outbound?.flight?`去 ${state.flights.outbound.flight} ${state.flights.outbound.departTime||''} · 回 ${state.flights.return?.flight||'待設定'}`:'日期、機場、起降時間','flight')}${card('🏨','STAY',state.stays.length?`${state.stays.length} 間住宿`:'設定住宿',staySub,'stay')}${card('🚗','TRANSPORT',state.meta.transport||'自駕',state.meta.rentalCompany||'點此設定租車 / 包車','transport')}${card('👨‍👩‍👦','TRAVEL PARTY',state.party.map(p=>p.type+(p.age?' '+p.age+'歲':'')).join(' · '),state.party.map(p=>p.name).join(' · '),'party')}<div class="box"><div class="boxHead"><div><small>FAMILY MODE</small><b>家庭節奏</b></div><span>👨‍👩‍👦</span></div>${[['toddler','幼童同行'],['elderly','長輩同行'],['stroller','攜帶推車'],['nap','保留午休'],['relaxed','不要排太趕']].map(([k,l])=>`<label class="toggle"><span>${l}</span><input type="checkbox" ${state.family[k]?'checked':''} onchange="app.family('${k}',this.checked)"></label>`).join('')}</div>${card('💰','BUDGET',`NT$ ${total.toLocaleString()}`,`預算 ${Number(state.meta.budgetTarget||0).toLocaleString()} · 剩餘 ${(Number(state.meta.budgetTarget||0)-total).toLocaleString()}`,'budget')}<div class="daysPick"><b>旅行天數</b><div>${[3,4,5,6,7,8,9,10].map(n=>`<button class="dayBtn ${state.days===n?'selected':''}" onclick="app.days(${n})">${n}</button>`).join('')}</div></div><div class="dataTools"><button class="btn outline small" onclick="app.exportData()">匯出資料</button><label class="btn outline small">匯入資料<input type="file" accept="application/json" hidden onchange="app.importData(this.files[0])"></label></div>`}
function mapView(){const t=trip(),stay=state.stays.find(s=>state.day>=Number(s.fromDay)&&state.day<=Number(s.toDay)),usable=t.filter(x=>x.value&&x.value!=='待安排'&&x.value!=='飯店早餐');return `${dayTabs()}<div class="mapHero"><span style="font-size:34px">📍</span><h2>DAY ${state.day} Route</h2><p>${stay?`已套用 DAY ${state.day} 住宿：${esc(stay.hotel)}`:`DAY ${state.day} 未設定住宿`}</p><button class="btn primary" onclick="app.route()">🧭 全日路線預覽</button></div><button class="stopBtn" onclick="app.route()"><b>${usable.length} STOPS</b><span>開啟 Google Maps</span><b>🧭</b></button><div class="routeList">${t.map((s,i)=>`<div class="routeRow"><span>${i+1}</span><div><small>${s.name}</small><b>${esc(s.value)}</b></div><button class="btn secondary small" onclick="app.navTo('${encodeURIComponent(s.value)}')">🧭 導航</button></div>`).join('')}</div><p class="tiny">全日預覽最多帶入 3 個中途點；站點多時請使用逐站導航。</p>`}
function placeList(){const q=state.explore.q.toLowerCase(),f=stat